Search/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('base.urls')),
    path('', include('authenticate.urls')),   
]

authenticate/urls.py
from django.urls import path, include
from . import views

app_name = 'auth_app'
urlpatterns = [
    path('login/', views.loginPage, name='login'),
    path('register/', views.register, name='register'),
    path('signOut/', views.signOut, name='logout'),
    path('sudo/', views.superUserDo, name='sudo'),
]

base/urls.py
from django.urls import path, include
from . import views

app_name = 'base_app'
urlpatterns = [
    path('', views.home, name='home'),
    path('addStudent/', views.addStudent, name='add'),
    path('delete/<str:pk>/', views.delete, name='delete'),
    path('modify/<str:pk>/', views.modify, name='modify'),
]

authenticate/models.py
from django.db import models

# Create your models here.

base/models.py
from django.db import models

# Create your models here.
class Student(models.Model):
    classes = [
        ('5th', 'Class 5th'),
        ('6th', 'Class 6th'),
        ('7th', 'Class 7th'),
        ('8th', 'Class 8th'),
        ('9th', 'Class 9th'),
        ('10th', 'Class 10th'),
    ]
    name = models.CharField(max_length=100, verbose_name='Student Name')
    email = models.EmailField(max_length=100, null=True)
    phone = models.IntegerField()
    grade = models.CharField(max_length=100, choices=classes)
    dob = models.DateField(auto_now_add=False, verbose_name='Date of Birth')
    marks =  models.IntegerField(verbose_name='Percentage')
    address = models.CharField(max_length=200, null=True, blank=True)
    city = models.CharField(max_length=100, null=True, blank=True)
    state = models.CharField(max_length=100, null=True, blank=True)
    enrolledDate = models.DateTimeField(auto_now_add=True, null=True)
    
    
    def __str__(self):
        return self.name

base/forms.py
from django.forms import ModelForm
from django import forms
from .models import Student

class StudentForm(ModelForm):
    class Meta:
        model = Student
        fields = '__all__'

authenticate/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.contrib.auth.models import User, Group
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from .decorators import unauthenticated_user, allowed_users

# Create your views here.
@unauthenticated_user
def loginPage(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['Password']
        
        
        userToAuth = authenticate(request, username=username, password=password)
        
        if userToAuth is not None:
            login(request, userToAuth)
            # Checking if a GET next request exists
            if 'next' in request.POST:
                return redirect(request.POST.get("next"))
            else:
                return redirect('/')
            
        else:
            messages.error(request, 'One or more Credentials are incorrect')
            return redirect('auth_app:login')  
            
    return render(request, 'auths/login.html')

@unauthenticated_user
def register(request):
    if request.method == 'POST':
        #username = request.POST['username']
        username = request.POST.get('username')
        email = request.POST.get('email')
        fname = request.POST.get('fname')
        lname = request.POST.get('lname')
        password1 = request.POST.get('Password1')
        password2 = request.POST.get('Password2')
        
        if User.objects.filter(username=username):
            messages.error(request, 'Username already in use choose another!')
            return redirect('auth_app:register')
        if User.objects.filter(email=email):
            messages.error(request, 'Email already exist!')
            return redirect('auth_app:register')
        if len(username) > 10:
            messages.error(request, 'Username must be under 10 character')
            return redirect('auth_app:register')
        if password1 != password2:
            messages.error(request, 'Passwords do not match!')
            return redirect('auth_app:register')
        if not username.isalnum():
            messages.error(request, 'Username must be Alpha-Numeric!')
            return redirect('auth_app:register')
        else:
            newUser =  User.objects.create_user(username=username, email=email, password=password2, first_name=fname, last_name=lname)
            newUser.save()
            # Add customer to a group automatically
            group = Group.objects.get(name='users')
            newUser.groups.add(group)
            
            messages.success(request, 'Account was created for ' + username)

            
            return redirect('auth_app:login')
    return render(request, 'auths/register.html')

def signOut(request):
    logout(request)
    messages.success(request, 'Logged out successfully')
    return redirect('/')


@login_required(login_url='auth_app:login') #add redirect functionality
@allowed_users(allowed_roles=['admin'])
def superUserDo(request):
    return HttpResponse('This is a clear case of privilege escalation!!!!!!')

base/views.py
from django.shortcuts import render, redirect
from .models import Student
from .forms import StudentForm
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

# Create your views here.
def home(request):
    students = Student.objects.all()
    paginator = Paginator(students, 4)
    page = request.GET.get('page')
    try:
        studs = paginator.page(page)
    except PageNotAnInteger:
        studs = paginator.page(1)
    except EmptyPage:
        studs = paginator.page(paginator.num_pages)
    
    context = {'students': students, 'studs':studs}
    return render(request, 'index.html', context)

def addStudent(request):
    form = StudentForm()
    if request.method == 'POST':
        form = StudentForm(request.POST)
        if form.is_valid():
            form.save()   #Creates the user object
            return redirect('/')
    
    
    context = {'form': form}
    return render(request, 'addStudent.html', context)

def delete(request, pk):
    to_delete = Student.objects.get(id=pk)
    to_delete.delete()
    return redirect('/')

def modify(request, pk):
    toUpdate = Student.objects.get(id=pk)
    form = StudentForm(instance=toUpdate)
    if request.method == 'POST':
        form = StudentForm(request.POST, instance=toUpdate)
        if form.is_valid():
            form.save()
            return redirect('/')
    
    context = {'form': form}
    return render(request, 'modify.html', context)

templates/addStudent.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <title>Add Students</title>
    <style>
    .student{margin-top:100px; margin-bottom:100px;}
    .forms{box-shadow: 0 3px 6px rgba(0,0,0,0.16), 0 3px 6px rgba(0,0,0,0.23); padding-top:30px; padding-bottom:30px; border-bottom:2px blue solid;}
    /* width */
    ::-webkit-scrollbar {
      width: 10px;
    }

    /* Track */
    ::-webkit-scrollbar-track {
      background: #f1f1f1; 
    }
    
    /* Handle */
    ::-webkit-scrollbar-thumb {
      background: #888; 
    }

    /* Handle on hover */
    ::-webkit-scrollbar-thumb:hover {
      background: #555; 
    }    
    </style>
  </head>
  <body>
    <div class="col-lg-12 student">
    <div class="container">
    <div class="row">
    <div class="col-lg-12 text-center">
    <a href="{% url 'base_app:home' %}" class="btn btn-primary">Back</a>
    <h4>Add Student Information</h4> <br>
    </div>
    <div class="col-lg-6 mx-auto forms">
    <form action="" method="POST">
      {% csrf_token %}  <!-- format for sending data securely -->
      {{form.management_form}}
      {% for i in form %}
          {{i.label}}      {{i}}
          <hr>
      {% endfor %}
      <button class="btn btn-primary" type="submit">Add Student</button>
    </form>
    </div>
    </div>
    </div>
    </div>
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </body>
</html>

templates/auths/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Student Info</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <link rel="stylesheet" type="text/css" href="{% static '/css/main.css' %}">
</head>
<body>

    <!--{%  include 'auths/navbar.html' %}
	<div class="container-fluid">-->

    {% block content %}

    {% endblock %}
    
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.7/dist/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    
</body>
</html>

templates/auths/login.html
{% extends "auths/index.html" %}
{% load static %}
{% block content %}
	<style>
		body,
		html {
			margin: 0;
			padding: 0;
			height: 100%;
			background: #7abecc !important;
		}
		.user_card {
			width: 350px;
			margin-top: auto;
			margin-bottom: auto;
			background: #74cfbf;
			position: relative;
			display: flex;
			justify-content: center;
			flex-direction: column;
			padding: 10px;
			box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			-webkit-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			-moz-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			border-radius: 5px;

		}

		.form_container {
			margin-top: 20px;
		}

		#form-title{
			color: #fff;
			
		}

		.login_btn {
			width: 100%;
			background: #33ccff !important;
			color: white !important;
		}
		.login_btn:focus {
			box-shadow: none !important;
			outline: 0px !important;
		}
		.login_container {
			padding: 0 2rem;
		}
		.input-group-text {
			background: #f7ba5b !important;
			color: white !important;
			border: 0 !important;
			border-radius: 0.25rem 0 0 0.25rem !important;
		}
		.input_user,
		.input_pass:focus {
			box-shadow: none !important;
			outline: 0px !important;
		}

		#messages{
			background-color: grey;
			color: #fff;
			padding: 10px;
			margin-top: 10px;
		}
	</style>

</head>
<body>
	<div class="container h-100">
		<div class="d-flex justify-content-center h-100">
			<div class="user_card">
				<div class="d-flex justify-content-center">


					<h3 id="form-title">LOGIN</h3>
				</div>
				<div class="d-flex justify-content-center form_container">
					<form method="POST" action="">
						{% csrf_token %}
						<div class="input-group mb-3">
							<div class="input-group-append">
								<label for="" class="">Username</label>
								<input type="text" id="username"  name="username" placeholder="Input your username " Required>
							</div>
						</div>
						<br>
						<div class="input-group mb-2">
							<div class="input-group-append">
								<label for="" class="">Password</label>
								<input type="Password" id="Password"  name="Password" placeholder="Input Password" Required>
							</div>
						</div>
						{% if request.GET.next %}
							<input type= "hidden" name="next" value= "{{request.GET.next}}">
						{% endif %}

							<div class="d-flex justify-content-center mt-3 login_container">
				 				<input class="btn login_btn" type="submit" value="Login">
				   			</div>
					</form>

				</div>


				{% if messages %}
				<ul class="messages">
					{% for message in messages %}
					<li>
						{{ message }}
					</li>
					{% endfor %}
				</ul>
				{% endif %}

				<!-----{% for message in messages %}
					<p id="messages">{{message}}</p>
				{% endfor %}----->			
		
				<div class="mt-4">
					<div class="d-flex justify-content-center links">
						Don't have an account? <a href="{% url 'auth_app:register' %}" class="ml-2">Sign Up</a>
					</div>
			
				</div>
			</div>
		</div>
	</div>
</body>

{% endblock %}

templates/auths/navbar.html
{% load static %}


<style>
  .hello-msg{
    font-size: 18px;
    color: #fff;
    margin-right: 20px;
  }
</style>

<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <!----<img src="{% static 'images/logo.png' %}"> ---->
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  
  {% if user.is_authenticated %}
  <span class="hello-msg">Hello, {{request.user}}</span>
  <span ><a  class="hello-msg" href="{% url 'auth_app:logout' %}">Logout</a></span>
  {% endif %}

</nav>

templates/index.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <title>Student Dashboard</title>
  </head>
  <body>
    <nav class="navbar navbar-dark bg-primary navbar-expand-lg ">
      <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'base_app:home' %}">Student Info Viewer </a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <form class="d-flex" role="search">
            <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
            <button class="btn btn-outline-success" type="submit">Search</button>
          </form>
        </div>
        {% if not request.user.is_authenticated %}
        <div class="collapse navbar-collapse">
          <span ><a  class="btn btn-outline-warning" href="{% url 'auth_app:login' %}">Login</a></span>
          <span ><a  class="btn btn-outline-warning" href="{% url 'auth_app:register' %}">Register</a></span>
        </div>
        {% endif %}
        <span class="hello-msg">Hello, {{request.user}}</span>
      </div>
      {% if request.user.is_authenticated %}
      <span ><a  class="btn btn-outline-warning" href="{% url 'auth_app:logout' %}">Logout</a></span>
      {% endif %}
    </nav>
    <div class="col-lg-12">
    <div class="container">
    <div class="row">
    <div class="col-lg-12">
    <div class="row">
    <div class="col-lg-12 text-center mt-5">
    <h4>Students Information</h4> <br>
    </div>
    {% if request.user.is_authenticated %}
      {% if request.user.is_staff %}
      <div class="col-lg-6 mt-5 mb-5">
      <a href="{% url 'base_app:add' %}" class="btn btn-primary">Add New Student</a>
      </div>
      {% endif %}
    {% endif %}
    <div class="col-lg-6"></div>
    </div>
    </div>
    <table class="table table-hover" style="height:300px; overflow-y:scroll; border-bottom:2px blue solid;">
  <thead>
    <tr>
      <th scope="col">S.No</th>
      <th scope="col">Student ID</th>
      <th scope="col">Student Name</th>
      <th scope="col">Email</th>
      <th scope="col">Phone</th>
      <th scope="col">Class</th>
      <th scope="col">Marks</th>
      {% if request.user.is_authenticated %}
      <th scope="col">Edit</th>
      <th scope="col"></th>
      {% endif %}
    </tr>
  </thead>
  <tbody>
    {% for i in students %}
    <tr>
      <th scope="row">{{forloop.counter}}</th>
      <th scope="row">{{i.id}}</th>
      <td>{{i.name}}</td>
      <td>{{i.email}}</td>
      <td>{{i.phone}}</td>
      <td>{{i.grade}}</td>
      <td>{{i.marks}}%</td>
      {% if request.user.is_authenticated %}
      <td><button type="button" class="btn btn-primary" data-toggle="modal" data-target="#demo{{i.id}}">
<i class="fa fa-eye" aria-hidden="true"></i> View Details
</button></td>
      {% comment %} <td> <a href=""> </a></td> {% endcomment %}
<div class="modal" id="demo{{i.id}}">
  <div class="modal-dialog">
    <div class="modal-content">
    <div class="modal-header">
        <h4 class="modal-title"> {{i.name}}'s Information</h4>
        <button type="button" class="close" data-dismiss="modal">&times;</button>
      </div>
<div class="modal-body">
  <p> <b> Student Name </b>: {{i.name}}</p>
  <p><b>Student Email </b>: {{i.email}}</p>
  <p><b>Student phone </b>: {{i.phone}}</p>
  <p><b>Class </b>: {{i.grade}}</p>
  <p><b>DOB </b> : {{i.dob}}</p>
  <p><b>Marks </b> : {{i.marks}}</p>
  <p><b>Address </b>: {{i.address}}</p>
  <p><b>City </b>: {{i.city}}</p>
  <p><b>State </b>: {{i.state}}</p>
  <p><b>Enrolled Date </b>: {{i.enrolledDate|date}}</p>
  </div>
</div>
</div>
</div>
      {% if request.user.is_staff %}
      <td><a href="{% url 'base_app:modify' i.id %}" class="btn btn-primary">Modify</a></td>
      <td><a href="{% url 'base_app:delete' i.id %}" class="btn btn-primary">Delete</a></td>
      {% endif %}
    {% endif %}
  </tr>
  {% endfor %}
  </tbody>
  
</table>
<nav aria-label="Page navigation example text-center">
{% if studs.has_other_pages %}
  <ul class="pagination">
    {% if studs.has_previous %}
      <li class="page-item"><a class="page-link" href="?page={{ studs.previous_page_number }}">&laquo;</a></li>
    {% else %}
      <li class="disabled page-item"><span class="page-link">&laquo;</span></li>
    {% endif %}
    {% for i in studs.paginator.page_range %}
      {% if studs.number == i %}
        <li class="page-item active"><span class="page-link"><!--{{ i }}}--> <span class="sr-only">(current)</span></span></li>
      {% else %}
        <li class="page-item"><a class="page-link" href="?page={{ i }}"><!--{{ i }}}--></a></li>
      {% endif %}
    {% endfor %}
    {% if studs.has_next %}
      <li class="page-item"><a class="page-link" href="?page={{ studs.next_page_number }}">&raquo;</a></li>
    {% else %}
      <li class="page-item disabled"><span>&raquo;</span></li>
    {% endif %}
  </ul>
{% endif %}
</nav> 
    </div>
    </div>
    </div>
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </body>
</html>

templates/modify.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <title>Update</title>
    <style>
    .student{margin-top:100px; margin-bottom:100px;}
    .forms{box-shadow: 0 3px 6px rgba(0,0,0,0.16), 0 3px 6px rgba(0,0,0,0.23); padding-top:30px; padding-bottom:30px; border-bottom:2px blue solid;}
    /* width */
    ::-webkit-scrollbar {
      width: 10px;
    }

    /* Track */
    ::-webkit-scrollbar-track {
      background: #f1f1f1; 
    }
    
    /* Handle */
    ::-webkit-scrollbar-thumb {
      background: #888; 
    }

    /* Handle on hover */
    ::-webkit-scrollbar-thumb:hover {
      background: #555; 
    }    
    </style>
  </head>
  <body>
    <div class="col-lg-12 student">
    <div class="container">
    <div class="row">
    <div class="col-lg-12 text-center">
    <a href="{% url 'base_app:home' %}" class="btn btn-primary">Back</a>
    <h4>Modify Student Information</h4> <br>
    </div>
    <div class="col-lg-6 mx-auto forms">
    <form action="" method="POST">
      {% csrf_token %}  <!-- format for sending data securely -->
      {{form.management_form}}
      {% for i in form %}
          {{i.label}}      {{i}}
          <hr>
      {% endfor %}
      <button class="btn btn-primary" type="submit">Update Student</button>
    </form>
    </div>
    </div>
    </div>
    </div>
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </body>
</html>